version: '3.8'
services:
  api01: &api01
    hostname: api02
    cap_add:
      - SYS_PTRACE
    build: .
    ports:
      - "3001:3000"
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs
      - ./my-httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./db:/usr/local/apache2/db
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "200MB"
  api02: 
    <<: *api01
    hostname: api02
    ports:
      - "3002:3000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"
    
networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1